name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them for later use."
inputs:
  caching:
    description: "Whether to cache the dependencies or not."
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether the cache was used or not."
    value: ${{ steps.set-output.outputs.used-cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      if: inputs.caching == 'true'
      id: cache
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash
      run: npm ci
    - name: Set output
      id: set-output
      shell: bash
      run: echo "used-cache='${{ steps.cache.outputs.cache-hit }}'" >> $GITHUB_OUTPUT
